### ISSUE TITLE
No SIM card Detected

### ISSUE THREAD

**Issue by Kcrams** [BambooIV/android_vendor_zte_nx503a#1]
Hi! I used your code to build my personal cm 12.1 , but when i compiled your source code i got that the smartphone didn't recognize the SIM card. I tried to switch with my friends' sim, but it didnt work. I tried to change radio and baseband file with no success. I tried to use your "tourfoodstuff" code to build another cm 12.1 with no success. How could i solve that? i successfully build my personal cm until 04/03 after this date i cant get my cm works with SIM. Can you help me? Thanks in advance.

**Comment by BambooIV** [comment]
weird,how about gentu's source tree?i have been tested and it worked on my device,did you choose the property branch?

**Comment by Kcrams** [comment]
I didnt try gentu device's tree, to be honest, i'm using cm 12.1 branch and for kernel LA.BF.1.1.1_rb1.26. 
My device is not lte capable, is it a problem? btw until 3rd April everything was good, after that date my SIM didnt work with the new compiled code. I have to switch baseband? What baseband do you use, i'm on h213, did i manage to go back to h212?

**Comment by Kcrams** [comment]
And i use twrp-2.8.6.1 by syhost, i red that in some cases the not detected sim problem could depend by recovery version.

**Comment by BambooIV** [comment]
i am using h213,but i have been upgrading to cm-13.0

**Comment by Kcrams** [comment]
So cm 13.0 is workin? I compiled it 1 week ago but my SIM didnt work, ad i didnt know that was a rom's problem or just a mine one

**Comment by BambooIV** [comment]
cm-12.1 works well,i get back to it just now.besides,cm-13.0 of nx503a ril works,i will push commit later

**Comment by Kcrams** [comment]
I'll wait your commit impatiently. I dont know how my sim isnt working with cm 12.1, maybe with cm 13.0 i will be luckier. Thank you
